
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}


repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation(libs.net.dv8tion.jda)
    implementation(libs.com.fasterxml.jackson.core.jackson.databind)
    implementation(libs.com.google.inject.guice)
    implementation(libs.com.google.code.gson)

    compileOnly(libs.org.projectlombok.lombok)
    annotationProcessor(libs.org.projectlombok.lombok)
}

group = "de.codedbygruba"
version = "1.0-SNAPSHOT"
description = "HypersBot"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes["Main-Class"] = "de.codedbygruba.HypersBot"
    }

    from(
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map {
            zipTree(it)
        }
    )
}
